Ticket 8 add a comment to article comments
cheesenbeans/fe-nc-news pull request #6
Opened 2023-05-31 14:35 UTC by cheesenbeans

2023-06-01 08:01 UTC, itsaliabdallah requested changes
Take a look at the way your comments are ordered as newest comments are showing at the bottom of a page instead of near the top where I would expect them to be and I think your backend should order them like that.

Like where this is heading, like the idea of showing the comment that the user has posted with a green border.

Please take a look into optimisticaly rendering the comments and resubmit.

2023-06-01 08:01 UTC, aloush-dev commented on src/components/AddAComment.jsx
> +    console.log(commentToAdd)
make sure you're removing console logs

2023-06-01 08:01 UTC, aloush-dev commented on src/components/AddAComment.jsx
> +  const [commentSuccessful, setCommentSuccessful] = useState(false)
This seems like a bit of unnecessary state if you were to optimistically render your comments you wouldn't need to keep track of a successful post using state.

2023-06-01 08:01 UTC, aloush-dev commented on src/components/AddAComment.jsx
> +    })}
Please refactor this to optimistically render the comments instead, take a look at the notes and let me know if you need pointing towards that section.

2023-06-01 09:39 UTC, cjplatten requested changes
This is still making an api call to render the comments and is not optimistically rendering the newly posted comment.
There also doesn't appear to be any feedback for if the comment fails to post.

2023-06-01 09:39 UTC, cjplatten commented on src/components/SingleArticle.jsx
> +  }, [commentsByArticleId]);
This is causing an infinite loop in your use effect. commentsByArticleId is set within the useEffect so the useEffect triggers itself. You will see this if you open the Network tab of the inspect in your browser.

2023-06-01 12:43 UTC, HannahBurks requested changes
Please see my requested amendment in regards to your optimistic rendering

2023-06-02 10:02 UTC, cjplatten requested changes
Very close! The comment is still opitimistically added to comment list if there is an error and the text stays in the comment box so it is easy to click the submit button multiple times and flood the api so i would suggest clearing the comment box after it is submitted

2023-06-02 10:15 UTC, merged